### ISSUE TITLE
Raspberry Pi Garden

### ISSUE THREAD

**Issue by mattdsteele** [mattdsteele/side-projects#14]
This is all @jmhobbs's fault.

Build something that gauges soil moisture, temperature and humidity. Hook it up to a sprinkler system/pump (for seedlings) or drip hose (outdoors)

Research:

* [Sensors](https://www.amazon.com/gp/product/B071NX3234/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=piddlerinther-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B071F4RDHY&linkId=5db951bc214e8cabafbf8394e1f1a46e&th=1)
* https://spin.atomicobject.com/2014/06/28/raspberry-pi-gardening/
* https://www.hackster.io/ben-eagan/raspberry-pi-automated-plant-watering-with-website-8af2dc

**Comment by jmhobbs** [comment]
I've got two spare DHT11's you can have.  I've also had lots of luck buying thermocouples and Arduino clones on AliExpress, FWIW.

**Comment by mattdsteele** [comment]
Just bought a boatload of sensors, so maybe we can consolidate our extras and become an artisanal Radio Shack.

**Comment by mattdsteele** [comment]
@jmhobbs Hey so I have questions!

How are you reading from the DHT11s? My plan was to do this all in JavaScript with Johnny-Five, but it looks like it requires a [I2C backpack]http://johnny-five.io/examples/multi-DHT11_I2C_NANO_BACKPACK/), which I don't know what that is but I'm pretty sure I don't have.

Also what db are you sending your events into? Googling around it looks like influxdb might be a fun option.

**Comment by jmhobbs** [comment]
No backpack for me, just a 1 wire interface.  I'm reading mine with https://github.com/adafruit/DHT-sensor-library.  I wrote pure Go to do it but it's very finicky for timing so it should be done in C, which is why I switched to an existing library.

I am using Influx, and it's great.  Setting up influx and grafana was a piece of cake.

**Comment by mattdsteele** [comment]
@jmhobbs I'm using the adafruit library too; do you get intermittent temperature spikes?

![image](https://user-images.githubusercontent.com/389077/37127230-7a112ef0-223a-11e8-829d-04a4bd4409cc.png)

I've got a 10k resistor hooked up, but don't know if I should just be throwing out weirdo readings?

**Comment by jmhobbs** [comment]
Yeah, I sometimes see way off readings.  I'm rolling up readings over 5-10 seconds and averaging, I also considered keeping a circular buffer of previous readings and throwing away ones that jumped too far too fast.  But yeah, I get weird reads occasionally.

![screen shot 2018-03-08 at 10 34 06 am](https://user-images.githubusercontent.com/115059/37163021-5aca259c-22bc-11e8-8338-011f1b522b35.png)

That's one that got averaged in and still pulled things down 30 points.  My thermocouple + MAX6675 reads steady as a rock though.

**Comment by mattdsteele** [comment]
Done and blogged.
