### ISSUE TITLE
Twitter purge

### ISSUE THREAD

**Issue by mattdsteele** [mattdsteele/side-projects#7]
Maybe run it on Amazon lambda

**Comment by mattdsteele** [comment]
https://gist.github.com/robinsloan/3688616

**Comment by zachleat** [comment]
It would be awesome if this moved your content into some kind of local website you could host yourself.

**Comment by mattdsteele** [comment]
https://twitter.com/BrandyLJensen/status/1026826302857375745

**Comment by mattdsteele** [comment]
https://github.com/vickylai/ephemeral prior artttttt

**Comment by mattdsteele** [comment]
https://github.com/mattdsteele/blumhouse

(built with 11ty @zachleat)
